version: "2"
services:
  db:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/123456
      - NEO4J_dbms_connector_http_listen__address=:7474
      - NEO4J_dbms_connector_https_listen__address=:6477
      - NEO4J_dbms_connector_bolt_listen__address=:7687
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/logs:/logs
      - $HOME/neo4j/import:/var/lib/neo4j/import
      - $HOME/neo4j/plugins:/plugins
  web:
    image: confusius/thesis-image
    depends_on:
      - db
    ports:
      - 8089:8080
    environment:
      - DATABASE_HOST=db #readme: NOT localhost
      - DATABASE_USERNAME=neo4j
      - DATABASE_PASSWORD=123456
      - DATABASE_PORT=7474
      - "JAVA_OPTS=-Dspring.profiles.active=container -Dspring.config.location=classpath:resources/application.properties"
